package Lexer;

public enum Types {
    /* Literals. */ IDENTIFIER, STRING, FLOAT, INTEGER,

    //OPERATORS
    L_PAREN, R_PAREN, L_CURLY, R_CURLY, L_BRACE, R_BRACE,
    NOTE_IN, NOTE_OUT, GREATER, LESS,
    BANG, COMMA, COLON, DOT, EQUAL, SEMICOLON, SLASH, STAR,
    MINUS, PLUS, MODULO, BIT_AND, BIT_X0R, DATA,

    //TWO CHARACTERS
    BANG_EQUAL, EQUAL_EQUAL, EXPONENT, LAMBDA_OUT, GREATER_EQUAL, LESS_EQUAL,

    // Keywords.
    LAMBDA_IN, CLOSURE,
    AND, OR, AS, IS, IF, ELSE, FALSE, TRUE,
    REPEAT, UNTIL, SKIP, STOP, VOID, RETURN,
    JOIN, MATCH, PRINT, VARIABLE, MODEL, SELF,

    EOF

}
